// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: garage.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GarageCoordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarageCoordinate) Reset() {
	*x = GarageCoordinate{}
	mi := &file_garage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarageCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarageCoordinate) ProtoMessage() {}

func (x *GarageCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarageCoordinate.ProtoReflect.Descriptor instead.
func (*GarageCoordinate) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{0}
}

func (x *GarageCoordinate) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GarageCoordinate) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Garage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coordinate    *GarageCoordinate      `protobuf:"bytes,3,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Garage) Reset() {
	*x = Garage{}
	mi := &file_garage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Garage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Garage) ProtoMessage() {}

func (x *Garage) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Garage.ProtoReflect.Descriptor instead.
func (*Garage) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{1}
}

func (x *Garage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Garage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Garage) GetCoordinate() *GarageCoordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

type GarageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Garage              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarageList) Reset() {
	*x = GarageList{}
	mi := &file_garage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarageList) ProtoMessage() {}

func (x *GarageList) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarageList.ProtoReflect.Descriptor instead.
func (*GarageList) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{2}
}

func (x *GarageList) GetList() []*Garage {
	if x != nil {
		return x.List
	}
	return nil
}

type GarageListByUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          map[string]*GarageList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarageListByUser) Reset() {
	*x = GarageListByUser{}
	mi := &file_garage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarageListByUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarageListByUser) ProtoMessage() {}

func (x *GarageListByUser) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarageListByUser.ProtoReflect.Descriptor instead.
func (*GarageListByUser) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{3}
}

func (x *GarageListByUser) GetList() map[string]*GarageList {
	if x != nil {
		return x.List
	}
	return nil
}

type GarageUserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarageUserId) Reset() {
	*x = GarageUserId{}
	mi := &file_garage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarageUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarageUserId) ProtoMessage() {}

func (x *GarageUserId) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarageUserId.ProtoReflect.Descriptor instead.
func (*GarageUserId) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{4}
}

func (x *GarageUserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GarageAndUserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Garage        *Garage                `protobuf:"bytes,2,opt,name=garage,proto3" json:"garage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarageAndUserId) Reset() {
	*x = GarageAndUserId{}
	mi := &file_garage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarageAndUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarageAndUserId) ProtoMessage() {}

func (x *GarageAndUserId) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarageAndUserId.ProtoReflect.Descriptor instead.
func (*GarageAndUserId) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{5}
}

func (x *GarageAndUserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GarageAndUserId) GetGarage() *Garage {
	if x != nil {
		return x.Garage
	}
	return nil
}

var File_garage_proto protoreflect.FileDescriptor

const file_garage_proto_rawDesc = "" +
	"\n" +
	"\fgarage.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\"L\n" +
	"\x10GarageCoordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\"e\n" +
	"\x06Garage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\n" +
	"coordinate\x18\x03 \x01(\v2\x17.model.GarageCoordinateR\n" +
	"coordinate\"/\n" +
	"\n" +
	"GarageList\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.model.GarageR\x04list\"\x95\x01\n" +
	"\x10GarageListByUser\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.model.GarageListByUser.ListEntryR\x04list\x1aJ\n" +
	"\tListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.model.GarageListR\x05value:\x028\x01\"'\n" +
	"\fGarageUserId\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Q\n" +
	"\x0fGarageAndUserId\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x06garage\x18\x02 \x01(\v2\r.model.GarageR\x06garage2t\n" +
	"\aGarages\x120\n" +
	"\x04List\x12\x13.model.GarageUserId\x1a\x11.model.GarageList\"\x00\x127\n" +
	"\x03Add\x12\x16.model.GarageAndUserId\x1a\x16.google.protobuf.Empty\"\x00B\tZ\a./modelb\x06proto3"

var (
	file_garage_proto_rawDescOnce sync.Once
	file_garage_proto_rawDescData []byte
)

func file_garage_proto_rawDescGZIP() []byte {
	file_garage_proto_rawDescOnce.Do(func() {
		file_garage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garage_proto_rawDesc), len(file_garage_proto_rawDesc)))
	})
	return file_garage_proto_rawDescData
}

var file_garage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_garage_proto_goTypes = []any{
	(*GarageCoordinate)(nil), // 0: model.GarageCoordinate
	(*Garage)(nil),           // 1: model.Garage
	(*GarageList)(nil),       // 2: model.GarageList
	(*GarageListByUser)(nil), // 3: model.GarageListByUser
	(*GarageUserId)(nil),     // 4: model.GarageUserId
	(*GarageAndUserId)(nil),  // 5: model.GarageAndUserId
	nil,                      // 6: model.GarageListByUser.ListEntry
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_garage_proto_depIdxs = []int32{
	0, // 0: model.Garage.coordinate:type_name -> model.GarageCoordinate
	1, // 1: model.GarageList.list:type_name -> model.Garage
	6, // 2: model.GarageListByUser.list:type_name -> model.GarageListByUser.ListEntry
	1, // 3: model.GarageAndUserId.garage:type_name -> model.Garage
	2, // 4: model.GarageListByUser.ListEntry.value:type_name -> model.GarageList
	4, // 5: model.Garages.List:input_type -> model.GarageUserId
	5, // 6: model.Garages.Add:input_type -> model.GarageAndUserId
	2, // 7: model.Garages.List:output_type -> model.GarageList
	7, // 8: model.Garages.Add:output_type -> google.protobuf.Empty
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_garage_proto_init() }
func file_garage_proto_init() {
	if File_garage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garage_proto_rawDesc), len(file_garage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_garage_proto_goTypes,
		DependencyIndexes: file_garage_proto_depIdxs,
		MessageInfos:      file_garage_proto_msgTypes,
	}.Build()
	File_garage_proto = out.File
	file_garage_proto_goTypes = nil
	file_garage_proto_depIdxs = nil
}
